Repository bugcrowd/vulnerability-rating-taxonomy, pull requests merged in 2019-04, with the labels that each got.

#240 Revert "Add Indicators of Compromise category"
  CHANGELOG.md
  mappings/cvss_v3/cvss_v3.json
  mappings/cwe/cwe.json
  mappings/remediation_advice/remediation_advice.json
  vulnerability-rating-taxonomy.json
Labels: development

#237 Add Automotive Security Misconfiguration mappings
  CHANGELOG.md
  mappings/cvss_v3/cvss_v3.json
  mappings/remediation_advice/remediation_advice.json
Labels: enhancement

#241 Add Race Condition
  CHANGELOG.md
  mappings/cvss_v3/cvss_v3.json
  mappings/cwe/cwe.json
  mappings/remediation_advice/remediation_advice.json
  vulnerability-rating-taxonomy.json
Labels: taxonomy change
