Repository bugcrowd/vulnerability-rating-taxonomy, pull requests merged in 2019-05, with the labels that each got.

#243 Add Cache Poisoning
  CHANGELOG.md
  mappings/cvss_v3/cvss_v3.json
  mappings/cwe/cwe.json
  mappings/remediation_advice/remediation_advice.json
  vulnerability-rating-taxonomy.json
Labels: taxonomy change

#245 Revert "Revert "Add Indicators of Compromise category""
  CHANGELOG.md
  mappings/cvss_v3/cvss_v3.json
  mappings/cwe/cwe.json
  mappings/remediation_advice/remediation_advice.json
  vulnerability-rating-taxonomy.json
Labels: development

#247 Update capitalization of Email Spoofing on non-email domain
  CHANGELOG.md
  vulnerability-rating-taxonomy.json
Labels: enhancement
